[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "usrn-matcher"
version = "0.2.0"
description = "A library to spatially join USRNs to any spatial dataset"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-sedona[db]==1.8.1",
    "duckdb>=1.5.2",
]

[dependency-groups]
dev = [
    "pytest==9.0.2",
]

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["usrn_matcher"]

[project.scripts]
usrn-matcher = "usrn_matcher.matcher:UsrnMatcher.cli"

[tool.pytest.ini_options]
pythonpath = ["."]
